/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq;


import co.charbox.domain.data.jooq.tables.Connection;
import co.charbox.domain.data.jooq.tables.ConnectionInfo;
import co.charbox.domain.data.jooq.tables.DeviceAuth;
import co.charbox.domain.data.jooq.tables.DeviceConfigs;
import co.charbox.domain.data.jooq.tables.Devices;
import co.charbox.domain.data.jooq.tables.Heartbeat;
import co.charbox.domain.data.jooq.tables.Location;
import co.charbox.domain.data.jooq.tables.Outage;
import co.charbox.domain.data.jooq.tables.Ping;
import co.charbox.domain.data.jooq.tables.ServerAuth;
import co.charbox.domain.data.jooq.tables.SimpleLocation;
import co.charbox.domain.data.jooq.tables.Sst;
import co.charbox.domain.data.jooq.tables.TokenAuth;
import co.charbox.domain.data.jooq.tables.Versions;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in charbot_0_1_0
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table charbot_0_1_0.connection
	 */
	public static final Connection CONNECTION = co.charbox.domain.data.jooq.tables.Connection.CONNECTION;

	/**
	 * The table charbot_0_1_0.connection_info
	 */
	public static final ConnectionInfo CONNECTION_INFO = co.charbox.domain.data.jooq.tables.ConnectionInfo.CONNECTION_INFO;

	/**
	 * The table charbot_0_1_0.devices
	 */
	public static final Devices DEVICES = co.charbox.domain.data.jooq.tables.Devices.DEVICES;

	/**
	 * The table charbot_0_1_0.device_auth
	 */
	public static final DeviceAuth DEVICE_AUTH = co.charbox.domain.data.jooq.tables.DeviceAuth.DEVICE_AUTH;

	/**
	 * The table charbot_0_1_0.device_configs
	 */
	public static final DeviceConfigs DEVICE_CONFIGS = co.charbox.domain.data.jooq.tables.DeviceConfigs.DEVICE_CONFIGS;

	/**
	 * The table charbot_0_1_0.heartbeat
	 */
	public static final Heartbeat HEARTBEAT = co.charbox.domain.data.jooq.tables.Heartbeat.HEARTBEAT;

	/**
	 * The table charbot_0_1_0.location
	 */
	public static final Location LOCATION = co.charbox.domain.data.jooq.tables.Location.LOCATION;

	/**
	 * The table charbot_0_1_0.outage
	 */
	public static final Outage OUTAGE = co.charbox.domain.data.jooq.tables.Outage.OUTAGE;

	/**
	 * The table charbot_0_1_0.ping
	 */
	public static final Ping PING = co.charbox.domain.data.jooq.tables.Ping.PING;

	/**
	 * The table charbot_0_1_0.server_auth
	 */
	public static final ServerAuth SERVER_AUTH = co.charbox.domain.data.jooq.tables.ServerAuth.SERVER_AUTH;

	/**
	 * The table charbot_0_1_0.simple_location
	 */
	public static final SimpleLocation SIMPLE_LOCATION = co.charbox.domain.data.jooq.tables.SimpleLocation.SIMPLE_LOCATION;

	/**
	 * The table charbot_0_1_0.sst
	 */
	public static final Sst SST = co.charbox.domain.data.jooq.tables.Sst.SST;

	/**
	 * The table charbot_0_1_0.token_auth
	 */
	public static final TokenAuth TOKEN_AUTH = co.charbox.domain.data.jooq.tables.TokenAuth.TOKEN_AUTH;

	/**
	 * The table charbot_0_1_0.versions
	 */
	public static final Versions VERSIONS = co.charbox.domain.data.jooq.tables.Versions.VERSIONS;
}
