/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables;


import co.charbox.domain.data.jooq.Charbot_0_1_0;
import co.charbox.domain.data.jooq.Keys;
import co.charbox.domain.data.jooq.tables.records.DeviceConfigsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceConfigs extends TableImpl<DeviceConfigsRecord> {

	private static final long serialVersionUID = -895204245;

	/**
	 * The reference instance of <code>charbot_0_1_0.device_configs</code>
	 */
	public static final DeviceConfigs DEVICE_CONFIGS = new DeviceConfigs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DeviceConfigsRecord> getRecordType() {
		return DeviceConfigsRecord.class;
	}

	/**
	 * The column <code>charbot_0_1_0.device_configs.id</code>.
	 */
	public final TableField<DeviceConfigsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>charbot_0_1_0.device_configs.device_id</code>.
	 */
	public final TableField<DeviceConfigsRecord, Integer> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>charbot_0_1_0.device_configs.version</code>.
	 */
	public final TableField<DeviceConfigsRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>charbot_0_1_0.device_configs.registered</code>.
	 */
	public final TableField<DeviceConfigsRecord, Byte> REGISTERED = createField("registered", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>charbot_0_1_0.device_configs.schedules</code>.
	 */
	public final TableField<DeviceConfigsRecord, byte[]> SCHEDULES = createField("schedules", org.jooq.impl.SQLDataType.BLOB, this, "");

	/**
	 * Create a <code>charbot_0_1_0.device_configs</code> table reference
	 */
	public DeviceConfigs() {
		this("device_configs", null);
	}

	/**
	 * Create an aliased <code>charbot_0_1_0.device_configs</code> table reference
	 */
	public DeviceConfigs(String alias) {
		this(alias, DEVICE_CONFIGS);
	}

	private DeviceConfigs(String alias, Table<DeviceConfigsRecord> aliased) {
		this(alias, aliased, null);
	}

	private DeviceConfigs(String alias, Table<DeviceConfigsRecord> aliased, Field<?>[] parameters) {
		super(alias, Charbot_0_1_0.CHARBOT_0_1_0, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<DeviceConfigsRecord, Integer> getIdentity() {
		return Keys.IDENTITY_DEVICE_CONFIGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<DeviceConfigsRecord> getPrimaryKey() {
		return Keys.KEY_DEVICE_CONFIGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<DeviceConfigsRecord>> getKeys() {
		return Arrays.<UniqueKey<DeviceConfigsRecord>>asList(Keys.KEY_DEVICE_CONFIGS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceConfigs as(String alias) {
		return new DeviceConfigs(alias, this);
	}

	/**
	 * Rename this table
	 */
	public DeviceConfigs rename(String name) {
		return new DeviceConfigs(name, null);
	}
}
