/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables;


import co.charbox.domain.data.jooq.Charbot_0_1_0;
import co.charbox.domain.data.jooq.Keys;
import co.charbox.domain.data.jooq.tables.records.DeviceAuthRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceAuth extends TableImpl<DeviceAuthRecord> {

	private static final long serialVersionUID = -187181939;

	/**
	 * The reference instance of <code>charbot_0_1_0.device_auth</code>
	 */
	public static final DeviceAuth DEVICE_AUTH = new DeviceAuth();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DeviceAuthRecord> getRecordType() {
		return DeviceAuthRecord.class;
	}

	/**
	 * The column <code>charbot_0_1_0.device_auth.id</code>.
	 */
	public final TableField<DeviceAuthRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>charbot_0_1_0.device_auth.device_id</code>.
	 */
	public final TableField<DeviceAuthRecord, Integer> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>charbot_0_1_0.device_auth.key</code>.
	 */
	public final TableField<DeviceAuthRecord, String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>charbot_0_1_0.device_auth.activated</code>.
	 */
	public final TableField<DeviceAuthRecord, Byte> ACTIVATED = createField("activated", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * Create a <code>charbot_0_1_0.device_auth</code> table reference
	 */
	public DeviceAuth() {
		this("device_auth", null);
	}

	/**
	 * Create an aliased <code>charbot_0_1_0.device_auth</code> table reference
	 */
	public DeviceAuth(String alias) {
		this(alias, DEVICE_AUTH);
	}

	private DeviceAuth(String alias, Table<DeviceAuthRecord> aliased) {
		this(alias, aliased, null);
	}

	private DeviceAuth(String alias, Table<DeviceAuthRecord> aliased, Field<?>[] parameters) {
		super(alias, Charbot_0_1_0.CHARBOT_0_1_0, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<DeviceAuthRecord, Integer> getIdentity() {
		return Keys.IDENTITY_DEVICE_AUTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<DeviceAuthRecord> getPrimaryKey() {
		return Keys.KEY_DEVICE_AUTH_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<DeviceAuthRecord>> getKeys() {
		return Arrays.<UniqueKey<DeviceAuthRecord>>asList(Keys.KEY_DEVICE_AUTH_PRIMARY, Keys.KEY_DEVICE_AUTH_DEVICE_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceAuth as(String alias) {
		return new DeviceAuth(alias, this);
	}

	/**
	 * Rename this table
	 */
	public DeviceAuth rename(String name) {
		return new DeviceAuth(name, null);
	}
}
