/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables;


import co.charbox.domain.data.jooq.Charbot_0_1_0;
import co.charbox.domain.data.jooq.Keys;
import co.charbox.domain.data.jooq.tables.records.SimpleLocationRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SimpleLocation extends TableImpl<SimpleLocationRecord> {

	private static final long serialVersionUID = -1024675376;

	/**
	 * The reference instance of <code>charbot_0_1_0.simple_location</code>
	 */
	public static final SimpleLocation SIMPLE_LOCATION = new SimpleLocation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SimpleLocationRecord> getRecordType() {
		return SimpleLocationRecord.class;
	}

	/**
	 * The column <code>charbot_0_1_0.simple_location.id</code>.
	 */
	public final TableField<SimpleLocationRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>charbot_0_1_0.simple_location.ip</code>.
	 */
	public final TableField<SimpleLocationRecord, String> IP = createField("ip", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>charbot_0_1_0.simple_location.lat</code>.
	 */
	public final TableField<SimpleLocationRecord, Double> LAT = createField("lat", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>charbot_0_1_0.simple_location.lon</code>.
	 */
	public final TableField<SimpleLocationRecord, Double> LON = createField("lon", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * Create a <code>charbot_0_1_0.simple_location</code> table reference
	 */
	public SimpleLocation() {
		this("simple_location", null);
	}

	/**
	 * Create an aliased <code>charbot_0_1_0.simple_location</code> table reference
	 */
	public SimpleLocation(String alias) {
		this(alias, SIMPLE_LOCATION);
	}

	private SimpleLocation(String alias, Table<SimpleLocationRecord> aliased) {
		this(alias, aliased, null);
	}

	private SimpleLocation(String alias, Table<SimpleLocationRecord> aliased, Field<?>[] parameters) {
		super(alias, Charbot_0_1_0.CHARBOT_0_1_0, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SimpleLocationRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SIMPLE_LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SimpleLocationRecord> getPrimaryKey() {
		return Keys.KEY_SIMPLE_LOCATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SimpleLocationRecord>> getKeys() {
		return Arrays.<UniqueKey<SimpleLocationRecord>>asList(Keys.KEY_SIMPLE_LOCATION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SimpleLocation as(String alias) {
		return new SimpleLocation(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SimpleLocation rename(String name) {
		return new SimpleLocation(name, null);
	}
}
