/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables;


import co.charbox.domain.data.jooq.Charbot_0_1_0;
import co.charbox.domain.data.jooq.Keys;
import co.charbox.domain.data.jooq.tables.records.SstRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sst extends TableImpl<SstRecord> {

	private static final long serialVersionUID = -918072659;

	/**
	 * The reference instance of <code>charbot_0_1_0.sst</code>
	 */
	public static final Sst SST = new Sst();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SstRecord> getRecordType() {
		return SstRecord.class;
	}

	/**
	 * The column <code>charbot_0_1_0.sst.id</code>.
	 */
	public final TableField<SstRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.device_id</code>.
	 */
	public final TableField<SstRecord, Integer> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.token</code>.
	 */
	public final TableField<SstRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.start_time</code>.
	 */
	public final TableField<SstRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.down_size</code>.
	 */
	public final TableField<SstRecord, Long> DOWN_SIZE = createField("down_size", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.down_duration</code>.
	 */
	public final TableField<SstRecord, Integer> DOWN_DURATION = createField("down_duration", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.down_speed</code>.
	 */
	public final TableField<SstRecord, Double> DOWN_SPEED = createField("down_speed", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.up_size</code>.
	 */
	public final TableField<SstRecord, Long> UP_SIZE = createField("up_size", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.up_duration</code>.
	 */
	public final TableField<SstRecord, Integer> UP_DURATION = createField("up_duration", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.up_speed</code>.
	 */
	public final TableField<SstRecord, Double> UP_SPEED = createField("up_speed", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.ping_duration</code>.
	 */
	public final TableField<SstRecord, Integer> PING_DURATION = createField("ping_duration", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.device_conn_id</code>.
	 */
	public final TableField<SstRecord, Integer> DEVICE_CONN_ID = createField("device_conn_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>charbot_0_1_0.sst.server_loc_id</code>.
	 */
	public final TableField<SstRecord, Integer> SERVER_LOC_ID = createField("server_loc_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>charbot_0_1_0.sst</code> table reference
	 */
	public Sst() {
		this("sst", null);
	}

	/**
	 * Create an aliased <code>charbot_0_1_0.sst</code> table reference
	 */
	public Sst(String alias) {
		this(alias, SST);
	}

	private Sst(String alias, Table<SstRecord> aliased) {
		this(alias, aliased, null);
	}

	private Sst(String alias, Table<SstRecord> aliased, Field<?>[] parameters) {
		super(alias, Charbot_0_1_0.CHARBOT_0_1_0, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SstRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SstRecord> getPrimaryKey() {
		return Keys.KEY_SST_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SstRecord>> getKeys() {
		return Arrays.<UniqueKey<SstRecord>>asList(Keys.KEY_SST_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Sst as(String alias) {
		return new Sst(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Sst rename(String name) {
		return new Sst(name, null);
	}
}
