/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables;


import co.charbox.domain.data.jooq.Charbot_0_1_0;
import co.charbox.domain.data.jooq.Keys;
import co.charbox.domain.data.jooq.tables.records.UdevRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Udev extends TableImpl<UdevRecord> {

	private static final long serialVersionUID = -832862740;

	/**
	 * The reference instance of <code>charbot_0_1_0.udev</code>
	 */
	public static final Udev UDEV = new Udev();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UdevRecord> getRecordType() {
		return UdevRecord.class;
	}

	/**
	 * The column <code>charbot_0_1_0.udev.id</code>.
	 */
	public final TableField<UdevRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>charbot_0_1_0.udev.device_id</code>.
	 */
	public final TableField<UdevRecord, Integer> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>charbot_0_1_0.udev.user_id</code>.
	 */
	public final TableField<UdevRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>charbot_0_1_0.udev</code> table reference
	 */
	public Udev() {
		this("udev", null);
	}

	/**
	 * Create an aliased <code>charbot_0_1_0.udev</code> table reference
	 */
	public Udev(String alias) {
		this(alias, UDEV);
	}

	private Udev(String alias, Table<UdevRecord> aliased) {
		this(alias, aliased, null);
	}

	private Udev(String alias, Table<UdevRecord> aliased, Field<?>[] parameters) {
		super(alias, Charbot_0_1_0.CHARBOT_0_1_0, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<UdevRecord, Integer> getIdentity() {
		return Keys.IDENTITY_UDEV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UdevRecord> getPrimaryKey() {
		return Keys.KEY_UDEV_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UdevRecord>> getKeys() {
		return Arrays.<UniqueKey<UdevRecord>>asList(Keys.KEY_UDEV_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Udev as(String alias) {
		return new Udev(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Udev rename(String name) {
		return new Udev(name, null);
	}
}
