/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables.records;


import co.charbox.domain.data.jooq.tables.ConnectionInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectionInfoRecord extends UpdatableRecordImpl<ConnectionInfoRecord> implements Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = -1000508302;

	/**
	 * Setter for <code>charbot_0_1_0.connection_info.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.connection_info.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>charbot_0_1_0.connection_info.connection_id</code>.
	 */
	public void setConnectionId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.connection_info.connection_id</code>.
	 */
	public Integer getConnectionId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>charbot_0_1_0.connection_info.location_id</code>.
	 */
	public void setLocationId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.connection_info.location_id</code>.
	 */
	public Integer getLocationId() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ConnectionInfo.CONNECTION_INFO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return ConnectionInfo.CONNECTION_INFO.CONNECTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return ConnectionInfo.CONNECTION_INFO.LOCATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getConnectionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getLocationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectionInfoRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectionInfoRecord value2(Integer value) {
		setConnectionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectionInfoRecord value3(Integer value) {
		setLocationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectionInfoRecord values(Integer value1, Integer value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ConnectionInfoRecord
	 */
	public ConnectionInfoRecord() {
		super(ConnectionInfo.CONNECTION_INFO);
	}

	/**
	 * Create a detached, initialised ConnectionInfoRecord
	 */
	public ConnectionInfoRecord(Integer id, Integer connectionId, Integer locationId) {
		super(ConnectionInfo.CONNECTION_INFO);

		setValue(0, id);
		setValue(1, connectionId);
		setValue(2, locationId);
	}
}
