/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables.records;


import co.charbox.domain.data.jooq.tables.DeviceConfigs;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceConfigsRecord extends UpdatableRecordImpl<DeviceConfigsRecord> implements Record5<Integer, Integer, Integer, Byte, byte[]> {

	private static final long serialVersionUID = -1772446211;

	/**
	 * Setter for <code>charbot_0_1_0.device_configs.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.device_configs.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>charbot_0_1_0.device_configs.device_id</code>.
	 */
	public void setDeviceId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.device_configs.device_id</code>.
	 */
	public Integer getDeviceId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>charbot_0_1_0.device_configs.version</code>.
	 */
	public void setVersion(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.device_configs.version</code>.
	 */
	public Integer getVersion() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>charbot_0_1_0.device_configs.registered</code>.
	 */
	public void setRegistered(Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.device_configs.registered</code>.
	 */
	public Byte getRegistered() {
		return (Byte) getValue(3);
	}

	/**
	 * Setter for <code>charbot_0_1_0.device_configs.schedules</code>.
	 */
	public void setSchedules(byte[] value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.device_configs.schedules</code>.
	 */
	public byte[] getSchedules() {
		return (byte[]) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Byte, byte[]> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Byte, byte[]> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return DeviceConfigs.DEVICE_CONFIGS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return DeviceConfigs.DEVICE_CONFIGS.DEVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return DeviceConfigs.DEVICE_CONFIGS.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field4() {
		return DeviceConfigs.DEVICE_CONFIGS.REGISTERED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field5() {
		return DeviceConfigs.DEVICE_CONFIGS.SCHEDULES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getDeviceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value4() {
		return getRegistered();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value5() {
		return getSchedules();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceConfigsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceConfigsRecord value2(Integer value) {
		setDeviceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceConfigsRecord value3(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceConfigsRecord value4(Byte value) {
		setRegistered(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceConfigsRecord value5(byte[] value) {
		setSchedules(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceConfigsRecord values(Integer value1, Integer value2, Integer value3, Byte value4, byte[] value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DeviceConfigsRecord
	 */
	public DeviceConfigsRecord() {
		super(DeviceConfigs.DEVICE_CONFIGS);
	}

	/**
	 * Create a detached, initialised DeviceConfigsRecord
	 */
	public DeviceConfigsRecord(Integer id, Integer deviceId, Integer version, Byte registered, byte[] schedules) {
		super(DeviceConfigs.DEVICE_CONFIGS);

		setValue(0, id);
		setValue(1, deviceId);
		setValue(2, version);
		setValue(3, registered);
		setValue(4, schedules);
	}
}
