/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables.records;


import co.charbox.domain.data.jooq.tables.DeviceAuth;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceAuthRecord extends UpdatableRecordImpl<DeviceAuthRecord> implements Record4<Integer, Integer, String, Byte> {

	private static final long serialVersionUID = 491824361;

	/**
	 * Setter for <code>charbot_0_1_0.device_auth.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.device_auth.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>charbot_0_1_0.device_auth.device_id</code>.
	 */
	public void setDeviceId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.device_auth.device_id</code>.
	 */
	public Integer getDeviceId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>charbot_0_1_0.device_auth.key</code>.
	 */
	public void setKey(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.device_auth.key</code>.
	 */
	public String getKey() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>charbot_0_1_0.device_auth.activated</code>.
	 */
	public void setActivated(Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.device_auth.activated</code>.
	 */
	public Byte getActivated() {
		return (Byte) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, Byte> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, Byte> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return DeviceAuth.DEVICE_AUTH.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return DeviceAuth.DEVICE_AUTH.DEVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return DeviceAuth.DEVICE_AUTH.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field4() {
		return DeviceAuth.DEVICE_AUTH.ACTIVATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getDeviceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value4() {
		return getActivated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceAuthRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceAuthRecord value2(Integer value) {
		setDeviceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceAuthRecord value3(String value) {
		setKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceAuthRecord value4(Byte value) {
		setActivated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DeviceAuthRecord values(Integer value1, Integer value2, String value3, Byte value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DeviceAuthRecord
	 */
	public DeviceAuthRecord() {
		super(DeviceAuth.DEVICE_AUTH);
	}

	/**
	 * Create a detached, initialised DeviceAuthRecord
	 */
	public DeviceAuthRecord(Integer id, Integer deviceId, String key, Byte activated) {
		super(DeviceAuth.DEVICE_AUTH);

		setValue(0, id);
		setValue(1, deviceId);
		setValue(2, key);
		setValue(3, activated);
	}
}
