/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables.records;


import co.charbox.domain.data.jooq.tables.Outage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OutageRecord extends UpdatableRecordImpl<OutageRecord> implements Record8<Integer, Integer, Timestamp, Timestamp, Integer, Byte, String, Integer> {

	private static final long serialVersionUID = -888057148;

	/**
	 * Setter for <code>charbot_0_1_0.outage.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.outage.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>charbot_0_1_0.outage.device_id</code>.
	 */
	public void setDeviceId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.outage.device_id</code>.
	 */
	public Integer getDeviceId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>charbot_0_1_0.outage.start_time</code>.
	 */
	public void setStartTime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.outage.start_time</code>.
	 */
	public Timestamp getStartTime() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>charbot_0_1_0.outage.end_time</code>.
	 */
	public void setEndTime(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.outage.end_time</code>.
	 */
	public Timestamp getEndTime() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>charbot_0_1_0.outage.duration</code>.
	 */
	public void setDuration(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.outage.duration</code>.
	 */
	public Integer getDuration() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>charbot_0_1_0.outage.confirmed</code>.
	 */
	public void setConfirmed(Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.outage.confirmed</code>.
	 */
	public Byte getConfirmed() {
		return (Byte) getValue(5);
	}

	/**
	 * Setter for <code>charbot_0_1_0.outage.type</code>.
	 */
	public void setType(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.outage.type</code>.
	 */
	public String getType() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>charbot_0_1_0.outage.connection_info_id</code>.
	 */
	public void setConnectionInfoId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.outage.connection_info_id</code>.
	 */
	public Integer getConnectionInfoId() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Timestamp, Timestamp, Integer, Byte, String, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Timestamp, Timestamp, Integer, Byte, String, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Outage.OUTAGE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Outage.OUTAGE.DEVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Outage.OUTAGE.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Outage.OUTAGE.END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Outage.OUTAGE.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field6() {
		return Outage.OUTAGE.CONFIRMED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Outage.OUTAGE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Outage.OUTAGE.CONNECTION_INFO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getDeviceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value6() {
		return getConfirmed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getConnectionInfoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OutageRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OutageRecord value2(Integer value) {
		setDeviceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OutageRecord value3(Timestamp value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OutageRecord value4(Timestamp value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OutageRecord value5(Integer value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OutageRecord value6(Byte value) {
		setConfirmed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OutageRecord value7(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OutageRecord value8(Integer value) {
		setConnectionInfoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OutageRecord values(Integer value1, Integer value2, Timestamp value3, Timestamp value4, Integer value5, Byte value6, String value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OutageRecord
	 */
	public OutageRecord() {
		super(Outage.OUTAGE);
	}

	/**
	 * Create a detached, initialised OutageRecord
	 */
	public OutageRecord(Integer id, Integer deviceId, Timestamp startTime, Timestamp endTime, Integer duration, Byte confirmed, String type, Integer connectionInfoId) {
		super(Outage.OUTAGE);

		setValue(0, id);
		setValue(1, deviceId);
		setValue(2, startTime);
		setValue(3, endTime);
		setValue(4, duration);
		setValue(5, confirmed);
		setValue(6, type);
		setValue(7, connectionInfoId);
	}
}
