/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables.records;


import co.charbox.domain.data.jooq.tables.Ping;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PingRecord extends UpdatableRecordImpl<PingRecord> implements Record10<Integer, Integer, Integer, Integer, Timestamp, String, Double, Double, Double, Double> {

	private static final long serialVersionUID = -1627943259;

	/**
	 * Setter for <code>charbot_0_1_0.ping.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>charbot_0_1_0.ping.device_id</code>.
	 */
	public void setDeviceId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.device_id</code>.
	 */
	public Integer getDeviceId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>charbot_0_1_0.ping.connection_id</code>.
	 */
	public void setConnectionId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.connection_id</code>.
	 */
	public Integer getConnectionId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>charbot_0_1_0.ping.server_location_id</code>.
	 */
	public void setServerLocationId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.server_location_id</code>.
	 */
	public Integer getServerLocationId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>charbot_0_1_0.ping.start_time</code>.
	 */
	public void setStartTime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.start_time</code>.
	 */
	public Timestamp getStartTime() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>charbot_0_1_0.ping.url</code>.
	 */
	public void setUrl(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.url</code>.
	 */
	public String getUrl() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>charbot_0_1_0.ping.packet_loss</code>.
	 */
	public void setPacketLoss(Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.packet_loss</code>.
	 */
	public Double getPacketLoss() {
		return (Double) getValue(6);
	}

	/**
	 * Setter for <code>charbot_0_1_0.ping.min_latency</code>.
	 */
	public void setMinLatency(Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.min_latency</code>.
	 */
	public Double getMinLatency() {
		return (Double) getValue(7);
	}

	/**
	 * Setter for <code>charbot_0_1_0.ping.avg_latency</code>.
	 */
	public void setAvgLatency(Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.avg_latency</code>.
	 */
	public Double getAvgLatency() {
		return (Double) getValue(8);
	}

	/**
	 * Setter for <code>charbot_0_1_0.ping.max_latency</code>.
	 */
	public void setMaxLatency(Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.ping.max_latency</code>.
	 */
	public Double getMaxLatency() {
		return (Double) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, Integer, Integer, Timestamp, String, Double, Double, Double, Double> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, Integer, Integer, Timestamp, String, Double, Double, Double, Double> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Ping.PING.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Ping.PING.DEVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Ping.PING.CONNECTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Ping.PING.SERVER_LOCATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Ping.PING.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Ping.PING.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field7() {
		return Ping.PING.PACKET_LOSS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field8() {
		return Ping.PING.MIN_LATENCY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field9() {
		return Ping.PING.AVG_LATENCY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field10() {
		return Ping.PING.MAX_LATENCY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getDeviceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getConnectionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getServerLocationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value7() {
		return getPacketLoss();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value8() {
		return getMinLatency();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value9() {
		return getAvgLatency();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value10() {
		return getMaxLatency();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value2(Integer value) {
		setDeviceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value3(Integer value) {
		setConnectionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value4(Integer value) {
		setServerLocationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value5(Timestamp value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value6(String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value7(Double value) {
		setPacketLoss(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value8(Double value) {
		setMinLatency(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value9(Double value) {
		setAvgLatency(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord value10(Double value) {
		setMaxLatency(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PingRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, String value6, Double value7, Double value8, Double value9, Double value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PingRecord
	 */
	public PingRecord() {
		super(Ping.PING);
	}

	/**
	 * Create a detached, initialised PingRecord
	 */
	public PingRecord(Integer id, Integer deviceId, Integer connectionId, Integer serverLocationId, Timestamp startTime, String url, Double packetLoss, Double minLatency, Double avgLatency, Double maxLatency) {
		super(Ping.PING);

		setValue(0, id);
		setValue(1, deviceId);
		setValue(2, connectionId);
		setValue(3, serverLocationId);
		setValue(4, startTime);
		setValue(5, url);
		setValue(6, packetLoss);
		setValue(7, minLatency);
		setValue(8, avgLatency);
		setValue(9, maxLatency);
	}
}
