/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables.records;


import co.charbox.domain.data.jooq.tables.TokenAuth;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenAuthRecord extends UpdatableRecordImpl<TokenAuthRecord> implements Record5<Integer, Timestamp, String, Integer, String> {

	private static final long serialVersionUID = -1809989154;

	/**
	 * Setter for <code>charbot_0_1_0.token_auth.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.token_auth.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>charbot_0_1_0.token_auth.expiration</code>.
	 */
	public void setExpiration(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.token_auth.expiration</code>.
	 */
	public Timestamp getExpiration() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>charbot_0_1_0.token_auth.token</code>.
	 */
	public void setToken(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.token_auth.token</code>.
	 */
	public String getToken() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>charbot_0_1_0.token_auth.asset_id</code>.
	 */
	public void setAssetId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.token_auth.asset_id</code>.
	 */
	public Integer getAssetId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>charbot_0_1_0.token_auth.service_name</code>.
	 */
	public void setServiceName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.token_auth.service_name</code>.
	 */
	public String getServiceName() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Timestamp, String, Integer, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Timestamp, String, Integer, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TokenAuth.TOKEN_AUTH.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return TokenAuth.TOKEN_AUTH.EXPIRATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TokenAuth.TOKEN_AUTH.TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return TokenAuth.TOKEN_AUTH.ASSET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TokenAuth.TOKEN_AUTH.SERVICE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getExpiration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getAssetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getServiceName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TokenAuthRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TokenAuthRecord value2(Timestamp value) {
		setExpiration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TokenAuthRecord value3(String value) {
		setToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TokenAuthRecord value4(Integer value) {
		setAssetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TokenAuthRecord value5(String value) {
		setServiceName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TokenAuthRecord values(Integer value1, Timestamp value2, String value3, Integer value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TokenAuthRecord
	 */
	public TokenAuthRecord() {
		super(TokenAuth.TOKEN_AUTH);
	}

	/**
	 * Create a detached, initialised TokenAuthRecord
	 */
	public TokenAuthRecord(Integer id, Timestamp expiration, String token, Integer assetId, String serviceName) {
		super(TokenAuth.TOKEN_AUTH);

		setValue(0, id);
		setValue(1, expiration);
		setValue(2, token);
		setValue(3, assetId);
		setValue(4, serviceName);
	}
}
