/**
 * This class is generated by jOOQ
 */
package co.charbox.domain.data.jooq.tables.records;


import co.charbox.domain.data.jooq.tables.Versions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VersionsRecord extends UpdatableRecordImpl<VersionsRecord> implements Record4<Integer, String, Long, String> {

	private static final long serialVersionUID = -2104171597;

	/**
	 * Setter for <code>charbot_0_1_0.versions.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.versions.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>charbot_0_1_0.versions.version</code>.
	 */
	public void setVersion(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.versions.version</code>.
	 */
	public String getVersion() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>charbot_0_1_0.versions.sort</code>.
	 */
	public void setSort(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.versions.sort</code>.
	 */
	public Long getSort() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>charbot_0_1_0.versions.install_script_url</code>.
	 */
	public void setInstallScriptUrl(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>charbot_0_1_0.versions.install_script_url</code>.
	 */
	public String getInstallScriptUrl() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Long, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Long, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Versions.VERSIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Versions.VERSIONS.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return Versions.VERSIONS.SORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Versions.VERSIONS.INSTALL_SCRIPT_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getSort();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getInstallScriptUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VersionsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VersionsRecord value2(String value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VersionsRecord value3(Long value) {
		setSort(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VersionsRecord value4(String value) {
		setInstallScriptUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VersionsRecord values(Integer value1, String value2, Long value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VersionsRecord
	 */
	public VersionsRecord() {
		super(Versions.VERSIONS);
	}

	/**
	 * Create a detached, initialised VersionsRecord
	 */
	public VersionsRecord(Integer id, String version, Long sort, String installScriptUrl) {
		super(Versions.VERSIONS);

		setValue(0, id);
		setValue(1, version);
		setValue(2, sort);
		setValue(3, installScriptUrl);
	}
}
